### ISSUE TITLE
Spooky - Halloween

### ISSUE THREAD

**Issue by DanCQ** [DanCQ/Spooky#1]
<a href="https://spooky.pages.dev/" target="_blank" >Spooky</a>
For fun, as Halloween approaches.
A good place for JavaScript animations.
Feel free to make suggestions, or to improve the site.

<a href="https://github.com/DanCQ/Spooky" target="_blank" >GitHub Repository</a>

**Comment by dhruvdabhi101** [comment]
Hello.. Can I Contribute ? I want to add A jumpscare..

**Comment by DanCQ** [comment]
Yes. Go ahead.

**Comment by DanCQ** [comment]
> 
Good job, Dhruv! 
Looks and works great. 
It's also unexpected, if you don't know about it.

**Comment by dhruvdabhi101** [comment]
> > 
> 
> Good job, Dhruv! Looks and works great. It's also unexpected, if you don't know about it.

Thank You Sir.
